### ISSUE TITLE
Implement support for v2 API

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-go#175]
Related: https://github.com/elastic/apm-server/issues/1237

- [x] Core v2 protocol (https://github.com/elastic/apm-agent-go/pull/180)
- [x] Unit test buffer size (#182)
- [x] Unit test request size (#182)
- [x] Reinstate schema validation unit tests (#182)
- [x] Unit test early server response / unread body (#183)
- [x] Unit test error flushing (#183)
- [x] Track entity types in ring buffer, to update discarded stats (#184)
- [x] Reinstate ELASTIC_APM_DEBUG messages (#185)
- [x] Move spans to top level (#188)
- [x] Update API and configuration docs (#190)
- ~~Parse v2 error responses~~
- ~~Update HTTP transport's timeout to better cater for streaming~~

**Comment by axw** [comment]
- Won't bother parsing the error responses for now. We just log them as-is.
- I'm going to see how we go with leaving the timeout as it is: from connection to response. Given a default request time of 10 seconds, this leaves 20 seconds for connection and server response, which should be fine.

**Comment by axw** [comment]
Tested opbeans-go, with https://github.com/elastic/apm-agent-go/pull/197. All looks good, closing this.
