### ISSUE TITLE
Agent v2 meta issue

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-go#654]
Meta issue for tracking breaking changes that should go into the next major version of the agent, v2.0.0.

- [x] https://github.com/elastic/apm-agent-go/issues/655
- [x] https://github.com/elastic/apm-agent-go/issues/775
- [x] https://github.com/elastic/apm-agent-go/issues/646
- [x] https://github.com/elastic/apm-agent-go/issues/465
- [x] https://github.com/elastic/apm-agent-go/issues/1184
- [x] https://github.com/elastic/apm-agent-go/issues/1136
- [x] https://github.com/elastic/apm-agent-go/issues/1194
- [x] confirm minimum supported Go version for v2

**Comment by axw** [comment]
@elastic/apm-agent-go this is done according to the check boxes, but I'd like it if everyone could have a look through the code and have a think about whether anything else can be removed or improved (requiring breaking changes) before we commit to v2. Like v1, I expect it to last for quite some time.

**Comment by simitt** [comment]
I went through the open issues, have you considered whether https://github.com/elastic/apm-agent-go/issues/773 should be implemented? If not, then we should probably close it, as this would be considered a breaking change.
