### ISSUE TITLE
[meta][docs] Align Go Agent documentation 

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-agent-go#681]
A meta issue for tracking Go documentation changes outlined in https://github.com/elastic/apm-dev/issues/425.

### Doc restructure
- [x] `master` - https://github.com/elastic/apm-agent-go/pull/682
- [x] `1.x` - Will be pushed to 1.x during the next release

### Build release notes to docs: 
More details: https://github.com/elastic/apm/issues/132.
The PRs in each group must be merged at the same time to prevent breaking the doc build.

#### `master`
- [x] `elastic/apm-agent-go` - https://github.com/elastic/apm-agent-go/pull/686
- [x] `elastic/docs` - https://github.com/elastic/docs/pull/1502

#### `1.x`
- [x] `elastic/apm-agent-go` - Temporary placeholder file: https://github.com/elastic/apm-agent-go/pull/688
- [x] `elastic/docs` - https://github.com/elastic/docs/pull/1503

**Comment by bmorelli25** [comment]
All done! Docs and release notes will show up in `1.x` after the next release. 👋
